Class {
	#name : #PltPlatypusMetaSchemasRepository,
	#superclass : #PlatypusCoreRepository,
	#category : #'Platypus-PlatypusMetaSchemasSchemaInstance'
}

{ #category : #'platypus-generated-accessing' }
PltPlatypusMetaSchemasRepository class >> generatedMetaDataSchemaInstanceName [
  ^#PltPlatypusMetaSchemasSchemaInstance


]

{ #category : #'platypus-generated-platypus-signature' }
PltPlatypusMetaSchemasRepository class >> iso10303P11Translater [
  ^'Platypus (c) LISYC EA3883, Universite de Bretagne occidentale. Brest.'


]

{ #category : #'platypus-generated-platypus-signature' }
PltPlatypusMetaSchemasRepository class >> translatedFromISO10303P11 [
  ^true


]

{ #category : #'platypus-generated-platypus-signature' }
PltPlatypusMetaSchemasRepository class >> vwNamespaceName [
  ^#Platypus


]
