Class {
	#name : #PltPlatypusExpressPrimitivesRepository,
	#superclass : #PlatypusCoreRepository,
	#category : #'Platypus-PlatypusExpressPrimitivesSchemaInstance'
}

{ #category : #'platypus-generated-accessing' }
PltPlatypusExpressPrimitivesRepository class >> generatedMetaDataSchemaInstanceName [
  ^#PltPlatypusExpressPrimitivesSchemaInstance


]

{ #category : #'platypus-generated-platypus-signature' }
PltPlatypusExpressPrimitivesRepository class >> iso10303P11Translater [
  ^'Platypus (c) LISYC EA3883, Universite de Bretagne occidentale. Brest.'


]

{ #category : #'platypus-generated-platypus-signature' }
PltPlatypusExpressPrimitivesRepository class >> translatedFromISO10303P11 [
  ^true


]

{ #category : #'platypus-generated-platypus-signature' }
PltPlatypusExpressPrimitivesRepository class >> vwNamespaceName [
  ^#Platypus


]
