Class {
	#name : #PTsAbstractVisitor,
	#superclass : #PlatypusCoreAbstractVisitor,
	#category : #'Platypus-ExpressToolsboxSchemaInstance'
}

{ #category : #'platypus-generated-platypus-signature' }
PTsAbstractVisitor class >> iso10303P11Translater [
	^ 'Platypus (c) LISYC EA3883, Universite de Bretagne occidentale. Brest.'


]

{ #category : #'platypus-generated-platypus-signature' }
PTsAbstractVisitor class >> translatedFromISO10303P11 [
	^ true


]

{ #category : #'platypus-generated-platypus-signature' }
PTsAbstractVisitor class >> vwNamespaceName [
	^ #PTs


]
