Extension { #name : #ExChdCoreEntity }

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaArrayType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaAttributeReference [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaBagType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaBooleanType [
	^ false


]

{ #category : #'*Express2Cheddar-RecordAndClassSchema-classifying' }
ExChdCoreEntity >> isExChdAdaClass [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdAdaClassDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdAdaClassRefDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaClassReference [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarConstantsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaConstant [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaDoubleType [
	^ false


]

{ #category : #'*Express2Cheddar-RecordAndClassSchema-classifying' }
ExChdCoreEntity >> isExChdAdaEntity [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaEnumeration [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaIntegerType [
	^ false


]

{ #category : #'*Express2Cheddar-AdaInterfaceSchema-classifying' }
ExChdCoreEntity >> isExChdAdaInterface [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaListType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaNamedTypeReference [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaNaturalType [
	^ false


]

{ #category : #'*Express2Cheddar-PackageSchema-classifying' }
ExChdCoreEntity >> isExChdAdaPackage [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaPrimitiveClassReference [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaPrimitiveType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaRealType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaRecordReference [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaSetType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdAdaUnboundedStringType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdAttributeDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdBasicAdaTypeGetter [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdBasicAdaTypeValueFormat [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdCheddarDefinedType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdCheddarEntityDefinition [
	^ false


]

{ #category : #'*Express2Cheddar-RecordAndClassSchema-classifying' }
ExChdCoreEntity >> isExChdCheddarFunctionPtr [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdCheddarLawType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdCheddarPrimitiveType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdCheddarPriorityRange [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdCheddarXmlIdType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdCollectionDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdCompositeDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdConstrainedArrayType [
	^ false


]

{ #category : #'*Express2Cheddar-DiscriminatedTypeSchema-classifying' }
ExChdCoreEntity >> isExChdDiscriminatedType [
	^ false


]

{ #category : #'*Express2Cheddar-DiscriminatedTypeSchema-classifying' }
ExChdCoreEntity >> isExChdDiscriminatedTypeDiscriminant [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdDiscriminatedTypeDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdDiscriminatedTypeRefDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-DiscriminatedTypeSchema-classifying' }
ExChdCoreEntity >> isExChdDiscriminatedTypeUnion [
	^ false


]

{ #category : #'*Express2Cheddar-DiscriminatedTypeSchema-classifying' }
ExChdCoreEntity >> isExChdDiscriminatedTypeUnionElementType [
	^ false


]

{ #category : #'*Express2Cheddar-DiscriminatedTypeSchema-classifying' }
ExChdCoreEntity >> isExChdDiscriminatedTypeUnionType [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdDomainDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdEntityDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdEntityRefDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdExplicitTypeReference [
	^ false


]

{ #category : #'*Express2Cheddar-PackageSchema-classifying' }
ExChdCoreEntity >> isExChdGenericPackageInstanciation [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdInScopeAttribute [
	^ false


]

{ #category : #'*Express2Cheddar-PackageSchema-classifying' }
ExChdCoreEntity >> isExChdPackageAlias [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdPackageDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdPragmaConvention [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdRangeType [
	^ false


]

{ #category : #'*Express2Cheddar-RecordAndClassSchema-classifying' }
ExChdCoreEntity >> isExChdRecord [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdRecordDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdRecordRefDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdRootDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdSimpleDomainDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDtdSchema-classifying' }
ExChdCoreEntity >> isExChdUnknownDomainDtdElement [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdUnmappedEntityDefinition [
	^ false


]

{ #category : #'*Express2Cheddar-CheddarDomainsSchema-classifying' }
ExChdCoreEntity >> isExChdUnmappedTypeReference [
	^ false


]
