Class {
	#name : 'ExChdExpress2cheddarRepository',
	#superclass : 'PlatypusCoreRepository',
	#category : 'Express2Cheddar-Express2cheddarSchemaInstance',
	#package : 'Express2Cheddar',
	#tag : 'Express2cheddarSchemaInstance'
}

{ #category : 'platypus-generated-accessing' }
ExChdExpress2cheddarRepository class >> generatedMetaDataSchemaInstanceName [
	^ #ExChdExpress2cheddarSchemaInstance


]

{ #category : 'platypus-generated-platypus-signature' }
ExChdExpress2cheddarRepository class >> iso10303P11Translater [
	^ 'Platypus (c) LISYC EA3883, Universite de Bretagne occidentale. Brest.'


]

{ #category : 'platypus-generated-platypus-signature' }
ExChdExpress2cheddarRepository class >> translatedFromISO10303P11 [
	^ true


]

{ #category : 'platypus-generated-platypus-signature' }
ExChdExpress2cheddarRepository class >> vwNamespaceName [
	^ #Express2Cheddar


]
