Class {
	#name : #Express2CheddarAbstractVisitor,
	#superclass : #PlatypusCoreAbstractVisitor,
	#category : #'Express2Cheddar-Express2cheddarSchemaInstance'
}

{ #category : #'platypus-generated-platypus-signature' }
Express2CheddarAbstractVisitor class >> iso10303P11Translater [
	^ 'Platypus (c) LISYC EA3883, Universite de Bretagne occidentale. Brest.'


]

{ #category : #'platypus-generated-platypus-signature' }
Express2CheddarAbstractVisitor class >> translatedFromISO10303P11 [
	^ true


]

{ #category : #'platypus-generated-platypus-signature' }
Express2CheddarAbstractVisitor class >> vwNamespaceName [
	^ #Express2Cheddar


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaArrayType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaAttributeReference: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaBagType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaBooleanType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingRecordAndClass' }
Express2CheddarAbstractVisitor >> acceptAdaClass: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptAdaClassDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptAdaClassRefDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaClassReference: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarConstants' }
Express2CheddarAbstractVisitor >> acceptAdaConstant: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaDoubleType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingRecordAndClass' }
Express2CheddarAbstractVisitor >> acceptAdaEntity: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaEnumeration: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaIntegerType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingAdaInterface' }
Express2CheddarAbstractVisitor >> acceptAdaInterface: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaListType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaNamedTypeReference: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaNaturalType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingPackage' }
Express2CheddarAbstractVisitor >> acceptAdaPackage: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaPrimitiveClassReference: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaPrimitiveType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaRealType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaRecordReference: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaSetType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptAdaUnboundedStringType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptAttributeDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptBasicAdaTypeGetter: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptBasicAdaTypeValueFormat: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptCheddarDefinedType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptCheddarEntityDefinition: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingRecordAndClass' }
Express2CheddarAbstractVisitor >> acceptCheddarFunctionPtr: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptCheddarLawType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptCheddarPrimitiveType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptCheddarPriorityRange: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptCheddarXmlIdType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptCollectionDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptCompositeDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptConstrainedArrayType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingDiscriminatedType' }
Express2CheddarAbstractVisitor >> acceptDiscriminatedType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingDiscriminatedType' }
Express2CheddarAbstractVisitor >> acceptDiscriminatedTypeDiscriminant: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptDiscriminatedTypeDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptDiscriminatedTypeRefDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingDiscriminatedType' }
Express2CheddarAbstractVisitor >> acceptDiscriminatedTypeUnion: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingDiscriminatedType' }
Express2CheddarAbstractVisitor >> acceptDiscriminatedTypeUnionElementType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingDiscriminatedType' }
Express2CheddarAbstractVisitor >> acceptDiscriminatedTypeUnionType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptDomainDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptEntityDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptEntityRefDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptExplicitTypeReference: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingPackage' }
Express2CheddarAbstractVisitor >> acceptGenericPackageInstanciation: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptInScopeAttribute: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingPackage' }
Express2CheddarAbstractVisitor >> acceptPackageAlias: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptPackageDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptPragmaConvention: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptRangeType: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingRecordAndClass' }
Express2CheddarAbstractVisitor >> acceptRecord: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptRecordDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptRecordRefDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptRootDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptSimpleDomainDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDtd' }
Express2CheddarAbstractVisitor >> acceptUnknownDomainDtdElement: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptUnmappedEntityDefinition: e [
	"my subclasses have to redefine it"

	


]

{ #category : #'platypus-generated-visitingCheddarDomains' }
Express2CheddarAbstractVisitor >> acceptUnmappedTypeReference: e [
	"my subclasses have to redefine it"

	


]
