Class {
	#name : #PTsExpressToolsboxRepository,
	#superclass : #PlatypusCoreRepository,
	#category : #'PTs-ExpressToolsboxSchemaInstance'
}

{ #category : #'platypus-generated-accessing' }
PTsExpressToolsboxRepository class >> generatedMetaDataSchemaInstanceName [
	^ #PTsExpressToolsboxSchemaInstance


]

{ #category : #'platypus-generated-platypus-signature' }
PTsExpressToolsboxRepository class >> iso10303P11Translater [
	^ 'Platypus (c) LISYC EA3883, Universite de Bretagne occidentale. Brest.'


]

{ #category : #'platypus-generated-platypus-signature' }
PTsExpressToolsboxRepository class >> translatedFromISO10303P11 [
	^ true


]

{ #category : #'platypus-generated-platypus-signature' }
PTsExpressToolsboxRepository class >> vwNamespaceName [
	^ #PTs


]
